"""initial

Revision ID: 4385dd82afd3
Revises: 
Create Date: 2026-05-22 23:46:38.496840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4385dd82afd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('native_language', sa.String(), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('sentences_spoken', sa.Integer(), nullable=False),
    sa.Column('mistakes_count', sa.Integer(), nullable=False),
    sa.Column('corrections_accepted', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_language', 'date', name='uq_progress_user_lang_date')
    )
    op.create_index('ix_progress_user_lang', 'progress', ['user_id', 'target_language'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_user_started', 'sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_voice', sa.Boolean(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('telegram_file_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mistakes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('original', sa.Text(), nullable=False),
    sa.Column('corrected', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mistakes_user_lang_seen', 'mistakes', ['user_id', 'target_language', 'last_seen_at'], unique=False)
    op.create_table('exercise_mistake',
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('mistake_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['mistake_id'], ['mistakes.id'], ),
    sa.PrimaryKeyConstraint('exercise_id', 'mistake_id')
    )
    op.drop_index(op.f('_ExerciseToMistake_B_index'), table_name='_ExerciseToMistake')
    op.drop_table('_ExerciseToMistake')
    op.drop_table('Exercise')
    op.drop_index(op.f('Mistake_userId_targetLanguage_lastSeenAt_idx'), table_name='Mistake')
    op.drop_table('Mistake')
    op.drop_index(op.f('Session_userId_startedAt_idx'), table_name='Session')
    op.drop_table('Session')
    op.drop_index(op.f('Progress_userId_targetLanguage_date_key'), table_name='Progress')
    op.drop_index(op.f('Progress_userId_targetLanguage_idx'), table_name='Progress')
    op.drop_table('Progress')
    op.drop_index(op.f('User_email_key'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Progress',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('targetLanguage', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sentencesSpoken', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('mistakesCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('correctionsAccepted', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('streakDays', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Progress_userId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('Progress_pkey'))
    )
    op.create_index(op.f('Progress_userId_targetLanguage_idx'), 'Progress', ['userId', 'targetLanguage'], unique=False)
    op.create_index(op.f('Progress_userId_targetLanguage_date_key'), 'Progress', ['userId', 'targetLanguage', 'date'], unique=True)
    op.create_table('Session',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('targetLanguage', sa.TEXT(), server_default=sa.text("'en'::text"), autoincrement=False, nullable=False),
    sa.Column('startedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('endedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Session_userId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('Session_pkey'))
    )
    op.create_index(op.f('Session_userId_startedAt_idx'), 'Session', ['userId', 'startedAt'], unique=False)
    op.create_table('_ExerciseToMistake',
    sa.Column('A', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('B', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['A'], ['Exercise.id'], name=op.f('_ExerciseToMistake_A_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['B'], ['Mistake.id'], name=op.f('_ExerciseToMistake_B_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('A', 'B', name=op.f('_ExerciseToMistake_AB_pkey'))
    )
    op.create_index(op.f('_ExerciseToMistake_B_index'), '_ExerciseToMistake', ['B'], unique=False)
    op.create_table('Exercise',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('targetLanguage', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('completedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Exercise_userId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('Exercise_pkey'))
    )
    op.create_table('Mistake',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('original', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('corrected', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('targetLanguage', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sessionId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('occurrenceCount', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('lastSeenAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sessionId'], ['Session.id'], name=op.f('Mistake_sessionId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Mistake_userId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('Mistake_pkey'))
    )
    op.create_index(op.f('Mistake_userId_targetLanguage_lastSeenAt_idx'), 'Mistake', ['userId', 'targetLanguage', 'lastSeenAt'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nativeLanguage', sa.TEXT(), server_default=sa.text("'it'::text"), autoincrement=False, nullable=False),
    sa.Column('targetLanguage', sa.TEXT(), server_default=sa.text("'en'::text"), autoincrement=False, nullable=False),
    sa.Column('onboardingCompleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('User_pkey'))
    )
    op.create_index(op.f('User_email_key'), 'User', ['email'], unique=True)
    op.drop_table('exercise_mistake')
    op.drop_index('ix_mistakes_user_lang_seen', table_name='mistakes')
    op.drop_table('mistakes')
    op.drop_table('messages')
    op.drop_index('ix_sessions_user_started', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_progress_user_lang', table_name='progress')
    op.drop_table('progress')
    op.drop_table('exercises')
    op.drop_table('users')
    # ### end Alembic commands ###
